name: Set up MacOS runner
# Schema: https://json.schemastore.org/github-action.json

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      uses: "./.github/actions/generic/environment"
    - name: Install ninja and libxml2 (MacOs)
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew update
        brew install ninja
        brew install libxml2
      shell: bash
    - name: Set up python
      uses: "./.github/actions/generic/python"
