all:
	cd test/UT&& $(MAKE) $@

run: txt xml html sonarqube json

txt:
	cd test/UT&& $(MAKE) $@

xml:
	cd test/UT&& $(MAKE) $@

html:
	cd test/UT&& $(MAKE) $@

sonarqube:
	cd test/UT&& $(MAKE) $@

json:
	cd test/UT&& $(MAKE) $@

clean:
	cd test/UT&& $(MAKE) $@
