name: Set up environment
# Schema: https://json.schemastore.org/github-action.json

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      run: |
        # Enable coverage for specific target configurations
        case "${{ matrix.os }}/${{ matrix.gcc }}/${{ matrix.python-version }}" in
          ubuntu-22.04/gcc-11/3.11) USE_COVERAGE=true ;;
          windows-2019/gcc-8/3.12)  USE_COVERAGE=true ;;
          macos-12/gcc-13/3.12)     USE_COVERAGE=true ;;
          macos-12/gcc/3.8)         USE_COVERAGE=true ;;
          *)                        USE_COVERAGE=false ;;
        esac
        echo "USE_COVERAGE=$USE_COVERAGE" >> $GITHUB_ENV

        # Set the CC environment
        echo "CC=${{ matrix.gcc }}" >> $GITHUB_ENV
      shell: bash
