# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #gcc: [gcc-5, gcc-8]
        gcc: [gcc-5]
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        python-version: [3.5, 3.6, 3.7, 3.8]

        #include:
        #  - os: windows-latest
        #    gcc: gcc
        #    python-version: 3.5
  
    steps:
    - uses: actions/checkout@v2
    - name: Install msys with GCC (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - name: Install GCC (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt-get install -y make ${{ matrix.gcc }} $(echo ${{ matrix.gcc }} | sed -e 's/gcc/g\+\+/')
        sudo apt-get clean
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        make setup-dev PYTHON=python
    - name: Lint with flake8
      run: |
        make lint PYTHON=python
    - name: Test with pytest
      run: |
        make test CC=${{ matrix.gcc }} PYTHON=python TEST_OPTS="--archive_differences"
    - name: Creating coverage report
      if: ${{ ( matrix.os == 'ubuntu-latest' ) && ( matrix.gcc == 'gcc-5' ) && ( matrix.python-version == '3.8' ) }}
      run: |
        codecov -X gcov search
      env: # Or as an environment variable
        super_secret: ${{ secrets.CODECOV_TOKEN }} 
    - name: Generate documentation
      run: |
        admin/release_checklist --no-verify-tags --no-verify-docs-next-version 4.2
        make doc PYTHON=python
    - name: Upload pytest test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: diffs-${{ matrix.os }}-${{ matrix.python-version }}
        path: gcovr/tests/diff.zip

  run-docker:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Run Docker
      run: |
        make docker-qa TEST_OPTS="--archive_differences"
    - name: Upload pytest test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: diffs-docker
        path: gcovr/tests/diff.zip
    